// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package user

import "gf-server/global"

var entity *Entity

// GetOne 查询单条数据
func GetOne(where ...interface{}) *Entity {
	res, err := Model.FindOne(where...)
	if err != nil {
		global.GFVA_LOG.Error("数据查询失败", err)
		return entity
	}

	return res
}
